FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

# Use 0.0.0.0 to make the server accessible outside the container
CMD ["python", "-u", "app.py"]